### ISSUE TITLE
MHW does not luanch if KT editor is downloaded

### ISSUE THREAD

**Issue by TheCommunistMexican** [jasonycw/MHW-Kulve-Taroth-Droprate-Editor#2]
- Version: [e.g. v165889]

**Describe the bug**
If the KT editor file is downloaded and installed into ProgramFiles(x86)\Steam\steamapps\common\Monster Hunter World\nativePC\common\equip then MHW is stuck on a black screen after launch. the only way to fix this is to uninstall the file from the equip folder.

**To Reproduce**
1. Go to 'Program Files (x86)\Steam\steamapps\common\Monster Hunter World\nativePC\common\equip'
2. Install 'em117_grade_lot.em117glt'
3. See blackscreen on startup

**Expected behavior**
Expected MHW to get to the title menu 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jasonycw** [comment]
Thanks for the report, seems like today's update breaks something with modding
https://www.nexusmods.com/monsterhunterworld/mods/473?tab=posts
https://forums.nexusmods.com/index.php?/topic/7119441-hexs-kt-adjustment/page-23#entry67067686

Will keep an eye out for when Hex will provide an updated droprate file 😉
https://twitter.com/MHhexhexhex/status/1087558666247593984

**Comment by TheCommunistMexican** [comment]
Thanks for the quick response!

**Comment by jasonycw** [comment]
Seems like Hex has updated the droprate file
https://twitter.com/MHhexhexhex/status/1088278008006234119

Will see what I can do tonight 😉

**Comment by jasonycw** [comment]
Update to support latest 165889 version's KT weapon droprate table ✌

~~Please help test it this Friday when KT live again~~
Edit: Tested 1 KT run, should be working
